# Generated by Django 3.1.4 on 2021-02-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20210221_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
