# Generated by Django 3.1.4 on 2021-02-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20210221_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
